### ISSUE TITLE
Run instructions in readme doesn't work

### ISSUE THREAD

**Issue by rsharifnasab** [cng-by-example/say-hello#1]
Hi
Suppose that I'm in the correct directory, running `npm build` would cause:
```
$ npm build       
Unknown command: "build"

Did you mean this?
    npm run build # run the "build" package script

To see a list of supported npm commands, run:
  npm help
```
I remembered that I should `npm install` first, but even after installing the node packages:
```
$ npm build             
Unknown command: "build"

Did you mean this?
    npm run build # run the "build" package script

To see a list of supported npm commands, run:
  npm help
```

I guess we should respect to the suggested message and run `npm run build` which do the right stuff. 

Other than that, maybe it worth mentioning that after go build we should run `./say-hello`.

**Comment by 1995parham** [comment]
Thanks for mentioning this, I have fixed it. :raised_hands:
